// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

type AgreementStatus string

const (
	AgreementStatus_AVAILABLE     AgreementStatus = "AVAILABLE"
	AgreementStatus_ERROR         AgreementStatus = "ERROR"
	AgreementStatus_NOT_AVAILABLE AgreementStatus = "NOT_AVAILABLE"
	AgreementStatus_PENDING       AgreementStatus = "PENDING"
)

type ApplicationType string

const (
	ApplicationType_ModelEvaluation ApplicationType = "ModelEvaluation"
	ApplicationType_RagEvaluation   ApplicationType = "RagEvaluation"
)

type AttributeType string

const (
	AttributeType_BOOLEAN     AttributeType = "BOOLEAN"
	AttributeType_NUMBER      AttributeType = "NUMBER"
	AttributeType_STRING      AttributeType = "STRING"
	AttributeType_STRING_LIST AttributeType = "STRING_LIST"
)

type AuthorizationStatus string

const (
	AuthorizationStatus_AUTHORIZED     AuthorizationStatus = "AUTHORIZED"
	AuthorizationStatus_NOT_AUTHORIZED AuthorizationStatus = "NOT_AUTHORIZED"
)

type AutomatedReasoningCheckLogicWarningType string

const (
	AutomatedReasoningCheckLogicWarningType_ALWAYS_FALSE AutomatedReasoningCheckLogicWarningType = "ALWAYS_FALSE"
	AutomatedReasoningCheckLogicWarningType_ALWAYS_TRUE  AutomatedReasoningCheckLogicWarningType = "ALWAYS_TRUE"
)

type AutomatedReasoningCheckResult string

const (
	AutomatedReasoningCheckResult_IMPOSSIBLE            AutomatedReasoningCheckResult = "IMPOSSIBLE"
	AutomatedReasoningCheckResult_INVALID               AutomatedReasoningCheckResult = "INVALID"
	AutomatedReasoningCheckResult_NO_TRANSLATION        AutomatedReasoningCheckResult = "NO_TRANSLATION"
	AutomatedReasoningCheckResult_SATISFIABLE           AutomatedReasoningCheckResult = "SATISFIABLE"
	AutomatedReasoningCheckResult_TOO_COMPLEX           AutomatedReasoningCheckResult = "TOO_COMPLEX"
	AutomatedReasoningCheckResult_TRANSLATION_AMBIGUOUS AutomatedReasoningCheckResult = "TRANSLATION_AMBIGUOUS"
	AutomatedReasoningCheckResult_VALID                 AutomatedReasoningCheckResult = "VALID"
)

type AutomatedReasoningPolicyAnnotationStatus string

const (
	AutomatedReasoningPolicyAnnotationStatus_APPLIED AutomatedReasoningPolicyAnnotationStatus = "APPLIED"
	AutomatedReasoningPolicyAnnotationStatus_FAILED  AutomatedReasoningPolicyAnnotationStatus = "FAILED"
)

type AutomatedReasoningPolicyBuildDocumentContentType string

const (
	AutomatedReasoningPolicyBuildDocumentContentType_pdf AutomatedReasoningPolicyBuildDocumentContentType = "pdf"
	AutomatedReasoningPolicyBuildDocumentContentType_txt AutomatedReasoningPolicyBuildDocumentContentType = "txt"
)

type AutomatedReasoningPolicyBuildMessageType string

const (
	AutomatedReasoningPolicyBuildMessageType_ERROR   AutomatedReasoningPolicyBuildMessageType = "ERROR"
	AutomatedReasoningPolicyBuildMessageType_INFO    AutomatedReasoningPolicyBuildMessageType = "INFO"
	AutomatedReasoningPolicyBuildMessageType_WARNING AutomatedReasoningPolicyBuildMessageType = "WARNING"
)

type AutomatedReasoningPolicyBuildResultAssetType string

const (
	AutomatedReasoningPolicyBuildResultAssetType_BUILD_LOG         AutomatedReasoningPolicyBuildResultAssetType = "BUILD_LOG"
	AutomatedReasoningPolicyBuildResultAssetType_POLICY_DEFINITION AutomatedReasoningPolicyBuildResultAssetType = "POLICY_DEFINITION"
	AutomatedReasoningPolicyBuildResultAssetType_QUALITY_REPORT    AutomatedReasoningPolicyBuildResultAssetType = "QUALITY_REPORT"
)

type AutomatedReasoningPolicyBuildWorkflowStatus string

const (
	AutomatedReasoningPolicyBuildWorkflowStatus_BUILDING         AutomatedReasoningPolicyBuildWorkflowStatus = "BUILDING"
	AutomatedReasoningPolicyBuildWorkflowStatus_CANCELLED        AutomatedReasoningPolicyBuildWorkflowStatus = "CANCELLED"
	AutomatedReasoningPolicyBuildWorkflowStatus_CANCEL_REQUESTED AutomatedReasoningPolicyBuildWorkflowStatus = "CANCEL_REQUESTED"
	AutomatedReasoningPolicyBuildWorkflowStatus_COMPLETED        AutomatedReasoningPolicyBuildWorkflowStatus = "COMPLETED"
	AutomatedReasoningPolicyBuildWorkflowStatus_FAILED           AutomatedReasoningPolicyBuildWorkflowStatus = "FAILED"
	AutomatedReasoningPolicyBuildWorkflowStatus_PREPROCESSING    AutomatedReasoningPolicyBuildWorkflowStatus = "PREPROCESSING"
	AutomatedReasoningPolicyBuildWorkflowStatus_SCHEDULED        AutomatedReasoningPolicyBuildWorkflowStatus = "SCHEDULED"
	AutomatedReasoningPolicyBuildWorkflowStatus_TESTING          AutomatedReasoningPolicyBuildWorkflowStatus = "TESTING"
)

type AutomatedReasoningPolicyBuildWorkflowType string

const (
	AutomatedReasoningPolicyBuildWorkflowType_IMPORT_POLICY  AutomatedReasoningPolicyBuildWorkflowType = "IMPORT_POLICY"
	AutomatedReasoningPolicyBuildWorkflowType_INGEST_CONTENT AutomatedReasoningPolicyBuildWorkflowType = "INGEST_CONTENT"
	AutomatedReasoningPolicyBuildWorkflowType_REFINE_POLICY  AutomatedReasoningPolicyBuildWorkflowType = "REFINE_POLICY"
)

type AutomatedReasoningPolicyTestRunResult string

const (
	AutomatedReasoningPolicyTestRunResult_FAILED AutomatedReasoningPolicyTestRunResult = "FAILED"
	AutomatedReasoningPolicyTestRunResult_PASSED AutomatedReasoningPolicyTestRunResult = "PASSED"
)

type AutomatedReasoningPolicyTestRunStatus string

const (
	AutomatedReasoningPolicyTestRunStatus_COMPLETED   AutomatedReasoningPolicyTestRunStatus = "COMPLETED"
	AutomatedReasoningPolicyTestRunStatus_FAILED      AutomatedReasoningPolicyTestRunStatus = "FAILED"
	AutomatedReasoningPolicyTestRunStatus_IN_PROGRESS AutomatedReasoningPolicyTestRunStatus = "IN_PROGRESS"
	AutomatedReasoningPolicyTestRunStatus_NOT_STARTED AutomatedReasoningPolicyTestRunStatus = "NOT_STARTED"
	AutomatedReasoningPolicyTestRunStatus_SCHEDULED   AutomatedReasoningPolicyTestRunStatus = "SCHEDULED"
)

type CommitmentDuration string

const (
	CommitmentDuration_OneMonth  CommitmentDuration = "OneMonth"
	CommitmentDuration_SixMonths CommitmentDuration = "SixMonths"
)

type CustomModelDeploymentStatus string

const (
	CustomModelDeploymentStatus_Active   CustomModelDeploymentStatus = "Active"
	CustomModelDeploymentStatus_Creating CustomModelDeploymentStatus = "Creating"
	CustomModelDeploymentStatus_Failed   CustomModelDeploymentStatus = "Failed"
)

type CustomizationType string

const (
	CustomizationType_CONTINUED_PRE_TRAINING CustomizationType = "CONTINUED_PRE_TRAINING"
	CustomizationType_DISTILLATION           CustomizationType = "DISTILLATION"
	CustomizationType_FINE_TUNING            CustomizationType = "FINE_TUNING"
	CustomizationType_IMPORTED               CustomizationType = "IMPORTED"
)

type EntitlementAvailability string

const (
	EntitlementAvailability_AVAILABLE     EntitlementAvailability = "AVAILABLE"
	EntitlementAvailability_NOT_AVAILABLE EntitlementAvailability = "NOT_AVAILABLE"
)

type EvaluationJobStatus string

const (
	EvaluationJobStatus_Completed  EvaluationJobStatus = "Completed"
	EvaluationJobStatus_Deleting   EvaluationJobStatus = "Deleting"
	EvaluationJobStatus_Failed     EvaluationJobStatus = "Failed"
	EvaluationJobStatus_InProgress EvaluationJobStatus = "InProgress"
	EvaluationJobStatus_Stopped    EvaluationJobStatus = "Stopped"
	EvaluationJobStatus_Stopping   EvaluationJobStatus = "Stopping"
)

type EvaluationJobType string

const (
	EvaluationJobType_Automated EvaluationJobType = "Automated"
	EvaluationJobType_Human     EvaluationJobType = "Human"
)

type EvaluationTaskType string

const (
	EvaluationTaskType_Classification    EvaluationTaskType = "Classification"
	EvaluationTaskType_Custom            EvaluationTaskType = "Custom"
	EvaluationTaskType_Generation        EvaluationTaskType = "Generation"
	EvaluationTaskType_QuestionAndAnswer EvaluationTaskType = "QuestionAndAnswer"
	EvaluationTaskType_Summarization     EvaluationTaskType = "Summarization"
)

type ExternalSourceType string

const (
	ExternalSourceType_BYTE_CONTENT ExternalSourceType = "BYTE_CONTENT"
	ExternalSourceType_S3           ExternalSourceType = "S3"
)

type FineTuningJobStatus string

const (
	FineTuningJobStatus_Completed  FineTuningJobStatus = "Completed"
	FineTuningJobStatus_Failed     FineTuningJobStatus = "Failed"
	FineTuningJobStatus_InProgress FineTuningJobStatus = "InProgress"
	FineTuningJobStatus_Stopped    FineTuningJobStatus = "Stopped"
	FineTuningJobStatus_Stopping   FineTuningJobStatus = "Stopping"
)

type FoundationModelLifecycleStatus string

const (
	FoundationModelLifecycleStatus_ACTIVE FoundationModelLifecycleStatus = "ACTIVE"
	FoundationModelLifecycleStatus_LEGACY FoundationModelLifecycleStatus = "LEGACY"
)

type GuardrailContentFilterAction string

const (
	GuardrailContentFilterAction_BLOCK GuardrailContentFilterAction = "BLOCK"
	GuardrailContentFilterAction_NONE  GuardrailContentFilterAction = "NONE"
)

type GuardrailContentFilterType string

const (
	GuardrailContentFilterType_HATE          GuardrailContentFilterType = "HATE"
	GuardrailContentFilterType_INSULTS       GuardrailContentFilterType = "INSULTS"
	GuardrailContentFilterType_MISCONDUCT    GuardrailContentFilterType = "MISCONDUCT"
	GuardrailContentFilterType_PROMPT_ATTACK GuardrailContentFilterType = "PROMPT_ATTACK"
	GuardrailContentFilterType_SEXUAL        GuardrailContentFilterType = "SEXUAL"
	GuardrailContentFilterType_VIOLENCE      GuardrailContentFilterType = "VIOLENCE"
)

type GuardrailContentFiltersTierName string

const (
	GuardrailContentFiltersTierName_CLASSIC  GuardrailContentFiltersTierName = "CLASSIC"
	GuardrailContentFiltersTierName_STANDARD GuardrailContentFiltersTierName = "STANDARD"
)

type GuardrailContextualGroundingAction string

const (
	GuardrailContextualGroundingAction_BLOCK GuardrailContextualGroundingAction = "BLOCK"
	GuardrailContextualGroundingAction_NONE  GuardrailContextualGroundingAction = "NONE"
)

type GuardrailContextualGroundingFilterType string

const (
	GuardrailContextualGroundingFilterType_GROUNDING GuardrailContextualGroundingFilterType = "GROUNDING"
	GuardrailContextualGroundingFilterType_RELEVANCE GuardrailContextualGroundingFilterType = "RELEVANCE"
)

type GuardrailFilterStrength string

const (
	GuardrailFilterStrength_HIGH   GuardrailFilterStrength = "HIGH"
	GuardrailFilterStrength_LOW    GuardrailFilterStrength = "LOW"
	GuardrailFilterStrength_MEDIUM GuardrailFilterStrength = "MEDIUM"
	GuardrailFilterStrength_NONE   GuardrailFilterStrength = "NONE"
)

type GuardrailManagedWordsType string

const (
	GuardrailManagedWordsType_PROFANITY GuardrailManagedWordsType = "PROFANITY"
)

type GuardrailModality string

const (
	GuardrailModality_IMAGE GuardrailModality = "IMAGE"
	GuardrailModality_TEXT  GuardrailModality = "TEXT"
)

type GuardrailPiiEntityType string

const (
	GuardrailPiiEntityType_ADDRESS                                 GuardrailPiiEntityType = "ADDRESS"
	GuardrailPiiEntityType_AGE                                     GuardrailPiiEntityType = "AGE"
	GuardrailPiiEntityType_AWS_ACCESS_KEY                          GuardrailPiiEntityType = "AWS_ACCESS_KEY"
	GuardrailPiiEntityType_AWS_SECRET_KEY                          GuardrailPiiEntityType = "AWS_SECRET_KEY"
	GuardrailPiiEntityType_CA_HEALTH_NUMBER                        GuardrailPiiEntityType = "CA_HEALTH_NUMBER"
	GuardrailPiiEntityType_CA_SOCIAL_INSURANCE_NUMBER              GuardrailPiiEntityType = "CA_SOCIAL_INSURANCE_NUMBER"
	GuardrailPiiEntityType_CREDIT_DEBIT_CARD_CVV                   GuardrailPiiEntityType = "CREDIT_DEBIT_CARD_CVV"
	GuardrailPiiEntityType_CREDIT_DEBIT_CARD_EXPIRY                GuardrailPiiEntityType = "CREDIT_DEBIT_CARD_EXPIRY"
	GuardrailPiiEntityType_CREDIT_DEBIT_CARD_NUMBER                GuardrailPiiEntityType = "CREDIT_DEBIT_CARD_NUMBER"
	GuardrailPiiEntityType_DRIVER_ID                               GuardrailPiiEntityType = "DRIVER_ID"
	GuardrailPiiEntityType_EMAIL                                   GuardrailPiiEntityType = "EMAIL"
	GuardrailPiiEntityType_INTERNATIONAL_BANK_ACCOUNT_NUMBER       GuardrailPiiEntityType = "INTERNATIONAL_BANK_ACCOUNT_NUMBER"
	GuardrailPiiEntityType_IP_ADDRESS                              GuardrailPiiEntityType = "IP_ADDRESS"
	GuardrailPiiEntityType_LICENSE_PLATE                           GuardrailPiiEntityType = "LICENSE_PLATE"
	GuardrailPiiEntityType_MAC_ADDRESS                             GuardrailPiiEntityType = "MAC_ADDRESS"
	GuardrailPiiEntityType_NAME                                    GuardrailPiiEntityType = "NAME"
	GuardrailPiiEntityType_PASSWORD                                GuardrailPiiEntityType = "PASSWORD"
	GuardrailPiiEntityType_PHONE                                   GuardrailPiiEntityType = "PHONE"
	GuardrailPiiEntityType_PIN                                     GuardrailPiiEntityType = "PIN"
	GuardrailPiiEntityType_SWIFT_CODE                              GuardrailPiiEntityType = "SWIFT_CODE"
	GuardrailPiiEntityType_UK_NATIONAL_HEALTH_SERVICE_NUMBER       GuardrailPiiEntityType = "UK_NATIONAL_HEALTH_SERVICE_NUMBER"
	GuardrailPiiEntityType_UK_NATIONAL_INSURANCE_NUMBER            GuardrailPiiEntityType = "UK_NATIONAL_INSURANCE_NUMBER"
	GuardrailPiiEntityType_UK_UNIQUE_TAXPAYER_REFERENCE_NUMBER     GuardrailPiiEntityType = "UK_UNIQUE_TAXPAYER_REFERENCE_NUMBER"
	GuardrailPiiEntityType_URL                                     GuardrailPiiEntityType = "URL"
	GuardrailPiiEntityType_USERNAME                                GuardrailPiiEntityType = "USERNAME"
	GuardrailPiiEntityType_US_BANK_ACCOUNT_NUMBER                  GuardrailPiiEntityType = "US_BANK_ACCOUNT_NUMBER"
	GuardrailPiiEntityType_US_BANK_ROUTING_NUMBER                  GuardrailPiiEntityType = "US_BANK_ROUTING_NUMBER"
	GuardrailPiiEntityType_US_INDIVIDUAL_TAX_IDENTIFICATION_NUMBER GuardrailPiiEntityType = "US_INDIVIDUAL_TAX_IDENTIFICATION_NUMBER"
	GuardrailPiiEntityType_US_PASSPORT_NUMBER                      GuardrailPiiEntityType = "US_PASSPORT_NUMBER"
	GuardrailPiiEntityType_US_SOCIAL_SECURITY_NUMBER               GuardrailPiiEntityType = "US_SOCIAL_SECURITY_NUMBER"
	GuardrailPiiEntityType_VEHICLE_IDENTIFICATION_NUMBER           GuardrailPiiEntityType = "VEHICLE_IDENTIFICATION_NUMBER"
)

type GuardrailSensitiveInformationAction string

const (
	GuardrailSensitiveInformationAction_ANONYMIZE GuardrailSensitiveInformationAction = "ANONYMIZE"
	GuardrailSensitiveInformationAction_BLOCK     GuardrailSensitiveInformationAction = "BLOCK"
	GuardrailSensitiveInformationAction_NONE      GuardrailSensitiveInformationAction = "NONE"
)

type GuardrailStatus string

const (
	GuardrailStatus_CREATING   GuardrailStatus = "CREATING"
	GuardrailStatus_DELETING   GuardrailStatus = "DELETING"
	GuardrailStatus_FAILED     GuardrailStatus = "FAILED"
	GuardrailStatus_READY      GuardrailStatus = "READY"
	GuardrailStatus_UPDATING   GuardrailStatus = "UPDATING"
	GuardrailStatus_VERSIONING GuardrailStatus = "VERSIONING"
)

type GuardrailTopicAction string

const (
	GuardrailTopicAction_BLOCK GuardrailTopicAction = "BLOCK"
	GuardrailTopicAction_NONE  GuardrailTopicAction = "NONE"
)

type GuardrailTopicType string

const (
	GuardrailTopicType_DENY GuardrailTopicType = "DENY"
)

type GuardrailTopicsTierName string

const (
	GuardrailTopicsTierName_CLASSIC  GuardrailTopicsTierName = "CLASSIC"
	GuardrailTopicsTierName_STANDARD GuardrailTopicsTierName = "STANDARD"
)

type GuardrailWordAction string

const (
	GuardrailWordAction_BLOCK GuardrailWordAction = "BLOCK"
	GuardrailWordAction_NONE  GuardrailWordAction = "NONE"
)

type InferenceProfileStatus_SDK string

const (
	InferenceProfileStatus_SDK_ACTIVE InferenceProfileStatus_SDK = "ACTIVE"
)

type InferenceProfileType string

const (
	InferenceProfileType_APPLICATION    InferenceProfileType = "APPLICATION"
	InferenceProfileType_SYSTEM_DEFINED InferenceProfileType = "SYSTEM_DEFINED"
)

type InferenceType string

const (
	InferenceType_ON_DEMAND   InferenceType = "ON_DEMAND"
	InferenceType_PROVISIONED InferenceType = "PROVISIONED"
)

type JobStatusDetails string

const (
	JobStatusDetails_Completed  JobStatusDetails = "Completed"
	JobStatusDetails_Failed     JobStatusDetails = "Failed"
	JobStatusDetails_InProgress JobStatusDetails = "InProgress"
	JobStatusDetails_NotStarted JobStatusDetails = "NotStarted"
	JobStatusDetails_Stopped    JobStatusDetails = "Stopped"
	JobStatusDetails_Stopping   JobStatusDetails = "Stopping"
)

type ModelCopyJobStatus string

const (
	ModelCopyJobStatus_Completed  ModelCopyJobStatus = "Completed"
	ModelCopyJobStatus_Failed     ModelCopyJobStatus = "Failed"
	ModelCopyJobStatus_InProgress ModelCopyJobStatus = "InProgress"
)

type ModelCustomization string

const (
	ModelCustomization_CONTINUED_PRE_TRAINING ModelCustomization = "CONTINUED_PRE_TRAINING"
	ModelCustomization_DISTILLATION           ModelCustomization = "DISTILLATION"
	ModelCustomization_FINE_TUNING            ModelCustomization = "FINE_TUNING"
)

type ModelCustomizationJobStatus string

const (
	ModelCustomizationJobStatus_Completed  ModelCustomizationJobStatus = "Completed"
	ModelCustomizationJobStatus_Failed     ModelCustomizationJobStatus = "Failed"
	ModelCustomizationJobStatus_InProgress ModelCustomizationJobStatus = "InProgress"
	ModelCustomizationJobStatus_Stopped    ModelCustomizationJobStatus = "Stopped"
	ModelCustomizationJobStatus_Stopping   ModelCustomizationJobStatus = "Stopping"
)

type ModelImportJobStatus string

const (
	ModelImportJobStatus_Completed  ModelImportJobStatus = "Completed"
	ModelImportJobStatus_Failed     ModelImportJobStatus = "Failed"
	ModelImportJobStatus_InProgress ModelImportJobStatus = "InProgress"
)

type ModelInvocationJobStatus string

const (
	ModelInvocationJobStatus_Completed          ModelInvocationJobStatus = "Completed"
	ModelInvocationJobStatus_Expired            ModelInvocationJobStatus = "Expired"
	ModelInvocationJobStatus_Failed             ModelInvocationJobStatus = "Failed"
	ModelInvocationJobStatus_InProgress         ModelInvocationJobStatus = "InProgress"
	ModelInvocationJobStatus_PartiallyCompleted ModelInvocationJobStatus = "PartiallyCompleted"
	ModelInvocationJobStatus_Scheduled          ModelInvocationJobStatus = "Scheduled"
	ModelInvocationJobStatus_Stopped            ModelInvocationJobStatus = "Stopped"
	ModelInvocationJobStatus_Stopping           ModelInvocationJobStatus = "Stopping"
	ModelInvocationJobStatus_Submitted          ModelInvocationJobStatus = "Submitted"
	ModelInvocationJobStatus_Validating         ModelInvocationJobStatus = "Validating"
)

type ModelModality string

const (
	ModelModality_EMBEDDING ModelModality = "EMBEDDING"
	ModelModality_IMAGE     ModelModality = "IMAGE"
	ModelModality_TEXT      ModelModality = "TEXT"
)

type ModelStatus string

const (
	ModelStatus_Active   ModelStatus = "Active"
	ModelStatus_Creating ModelStatus = "Creating"
	ModelStatus_Failed   ModelStatus = "Failed"
)

type OfferType string

const (
	OfferType_ALL    OfferType = "ALL"
	OfferType_PUBLIC OfferType = "PUBLIC"
)

type PerformanceConfigLatency string

const (
	PerformanceConfigLatency_optimized PerformanceConfigLatency = "optimized"
	PerformanceConfigLatency_standard  PerformanceConfigLatency = "standard"
)

type PromptRouterStatus string

const (
	PromptRouterStatus_AVAILABLE PromptRouterStatus = "AVAILABLE"
)

type PromptRouterType string

const (
	PromptRouterType_custom  PromptRouterType = "custom"
	PromptRouterType_default PromptRouterType = "default"
)

type ProvisionedModelStatus string

const (
	ProvisionedModelStatus_Creating  ProvisionedModelStatus = "Creating"
	ProvisionedModelStatus_Failed    ProvisionedModelStatus = "Failed"
	ProvisionedModelStatus_InService ProvisionedModelStatus = "InService"
	ProvisionedModelStatus_Updating  ProvisionedModelStatus = "Updating"
)

type QueryTransformationType string

const (
	QueryTransformationType_QUERY_DECOMPOSITION QueryTransformationType = "QUERY_DECOMPOSITION"
)

type RegionAvailability string

const (
	RegionAvailability_AVAILABLE     RegionAvailability = "AVAILABLE"
	RegionAvailability_NOT_AVAILABLE RegionAvailability = "NOT_AVAILABLE"
)

type RerankingMetadataSelectionMode string

const (
	RerankingMetadataSelectionMode_ALL       RerankingMetadataSelectionMode = "ALL"
	RerankingMetadataSelectionMode_SELECTIVE RerankingMetadataSelectionMode = "SELECTIVE"
)

type RetrieveAndGenerateType string

const (
	RetrieveAndGenerateType_EXTERNAL_SOURCES RetrieveAndGenerateType = "EXTERNAL_SOURCES"
	RetrieveAndGenerateType_KNOWLEDGE_BASE   RetrieveAndGenerateType = "KNOWLEDGE_BASE"
)

type S3InputFormat string

const (
	S3InputFormat_JSONL S3InputFormat = "JSONL"
)

type SearchType string

const (
	SearchType_HYBRID   SearchType = "HYBRID"
	SearchType_SEMANTIC SearchType = "SEMANTIC"
)

type SortByProvisionedModels string

const (
	SortByProvisionedModels_CreationTime SortByProvisionedModels = "CreationTime"
)

type SortJobsBy string

const (
	SortJobsBy_CreationTime SortJobsBy = "CreationTime"
)

type SortModelsBy string

const (
	SortModelsBy_CreationTime SortModelsBy = "CreationTime"
)

type SortOrder string

const (
	SortOrder_Ascending  SortOrder = "Ascending"
	SortOrder_Descending SortOrder = "Descending"
)

type Status string

const (
	Status_INCOMPATIBLE_ENDPOINT Status = "INCOMPATIBLE_ENDPOINT"
	Status_REGISTERED            Status = "REGISTERED"
)

type VectorSearchRerankingConfigurationType string

const (
	VectorSearchRerankingConfigurationType_BEDROCK_RERANKING_MODEL VectorSearchRerankingConfigurationType = "BEDROCK_RERANKING_MODEL"
)
