//go:build !ignore_autogenerated

// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutomatedReasoningPolicyBuildWorkflowSummary) DeepCopyInto(out *AutomatedReasoningPolicyBuildWorkflowSummary) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutomatedReasoningPolicyBuildWorkflowSummary.
func (in *AutomatedReasoningPolicyBuildWorkflowSummary) DeepCopy() *AutomatedReasoningPolicyBuildWorkflowSummary {
	if in == nil {
		return nil
	}
	out := new(AutomatedReasoningPolicyBuildWorkflowSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutomatedReasoningPolicySummary) DeepCopyInto(out *AutomatedReasoningPolicySummary) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutomatedReasoningPolicySummary.
func (in *AutomatedReasoningPolicySummary) DeepCopy() *AutomatedReasoningPolicySummary {
	if in == nil {
		return nil
	}
	out := new(AutomatedReasoningPolicySummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutomatedReasoningPolicyTestCase) DeepCopyInto(out *AutomatedReasoningPolicyTestCase) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutomatedReasoningPolicyTestCase.
func (in *AutomatedReasoningPolicyTestCase) DeepCopy() *AutomatedReasoningPolicyTestCase {
	if in == nil {
		return nil
	}
	out := new(AutomatedReasoningPolicyTestCase)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutomatedReasoningPolicyTestResult) DeepCopyInto(out *AutomatedReasoningPolicyTestResult) {
	*out = *in
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutomatedReasoningPolicyTestResult.
func (in *AutomatedReasoningPolicyTestResult) DeepCopy() *AutomatedReasoningPolicyTestResult {
	if in == nil {
		return nil
	}
	out := new(AutomatedReasoningPolicyTestResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomModelDeploymentSummary) DeepCopyInto(out *CustomModelDeploymentSummary) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.LastUpdatedAt != nil {
		in, out := &in.LastUpdatedAt, &out.LastUpdatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomModelDeploymentSummary.
func (in *CustomModelDeploymentSummary) DeepCopy() *CustomModelDeploymentSummary {
	if in == nil {
		return nil
	}
	out := new(CustomModelDeploymentSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomModelSummary) DeepCopyInto(out *CustomModelSummary) {
	*out = *in
	if in.CreationTime != nil {
		in, out := &in.CreationTime, &out.CreationTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomModelSummary.
func (in *CustomModelSummary) DeepCopy() *CustomModelSummary {
	if in == nil {
		return nil
	}
	out := new(CustomModelSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataProcessingDetails) DeepCopyInto(out *DataProcessingDetails) {
	*out = *in
	if in.CreationTime != nil {
		in, out := &in.CreationTime, &out.CreationTime
		*out = (*in).DeepCopy()
	}
	if in.LastModifiedTime != nil {
		in, out := &in.LastModifiedTime, &out.LastModifiedTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataProcessingDetails.
func (in *DataProcessingDetails) DeepCopy() *DataProcessingDetails {
	if in == nil {
		return nil
	}
	out := new(DataProcessingDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EvaluationSummary) DeepCopyInto(out *EvaluationSummary) {
	*out = *in
	if in.CreationTime != nil {
		in, out := &in.CreationTime, &out.CreationTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EvaluationSummary.
func (in *EvaluationSummary) DeepCopy() *EvaluationSummary {
	if in == nil {
		return nil
	}
	out := new(EvaluationSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FoundationModelDetails) DeepCopyInto(out *FoundationModelDetails) {
	*out = *in
	if in.ModelARN != nil {
		in, out := &in.ModelARN, &out.ModelARN
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FoundationModelDetails.
func (in *FoundationModelDetails) DeepCopy() *FoundationModelDetails {
	if in == nil {
		return nil
	}
	out := new(FoundationModelDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FoundationModelSummary) DeepCopyInto(out *FoundationModelSummary) {
	*out = *in
	if in.ModelARN != nil {
		in, out := &in.ModelARN, &out.ModelARN
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FoundationModelSummary.
func (in *FoundationModelSummary) DeepCopy() *FoundationModelSummary {
	if in == nil {
		return nil
	}
	out := new(FoundationModelSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GuardrailSummary) DeepCopyInto(out *GuardrailSummary) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GuardrailSummary.
func (in *GuardrailSummary) DeepCopy() *GuardrailSummary {
	if in == nil {
		return nil
	}
	out := new(GuardrailSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImportedModelSummary) DeepCopyInto(out *ImportedModelSummary) {
	*out = *in
	if in.CreationTime != nil {
		in, out := &in.CreationTime, &out.CreationTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImportedModelSummary.
func (in *ImportedModelSummary) DeepCopy() *ImportedModelSummary {
	if in == nil {
		return nil
	}
	out := new(ImportedModelSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InferenceProfile) DeepCopyInto(out *InferenceProfile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InferenceProfile.
func (in *InferenceProfile) DeepCopy() *InferenceProfile {
	if in == nil {
		return nil
	}
	out := new(InferenceProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InferenceProfile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InferenceProfileList) DeepCopyInto(out *InferenceProfileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InferenceProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InferenceProfileList.
func (in *InferenceProfileList) DeepCopy() *InferenceProfileList {
	if in == nil {
		return nil
	}
	out := new(InferenceProfileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InferenceProfileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InferenceProfileModel) DeepCopyInto(out *InferenceProfileModel) {
	*out = *in
	if in.ModelARN != nil {
		in, out := &in.ModelARN, &out.ModelARN
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InferenceProfileModel.
func (in *InferenceProfileModel) DeepCopy() *InferenceProfileModel {
	if in == nil {
		return nil
	}
	out := new(InferenceProfileModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InferenceProfileModelSource) DeepCopyInto(out *InferenceProfileModelSource) {
	*out = *in
	if in.CopyFrom != nil {
		in, out := &in.CopyFrom, &out.CopyFrom
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InferenceProfileModelSource.
func (in *InferenceProfileModelSource) DeepCopy() *InferenceProfileModelSource {
	if in == nil {
		return nil
	}
	out := new(InferenceProfileModelSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InferenceProfileSpec) DeepCopyInto(out *InferenceProfileSpec) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.InferenceProfileName != nil {
		in, out := &in.InferenceProfileName, &out.InferenceProfileName
		*out = new(string)
		**out = **in
	}
	if in.ModelSource != nil {
		in, out := &in.ModelSource, &out.ModelSource
		*out = new(InferenceProfileModelSource)
		(*in).DeepCopyInto(*out)
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*Tag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Tag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InferenceProfileSpec.
func (in *InferenceProfileSpec) DeepCopy() *InferenceProfileSpec {
	if in == nil {
		return nil
	}
	out := new(InferenceProfileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InferenceProfileStatus) DeepCopyInto(out *InferenceProfileStatus) {
	*out = *in
	if in.ACKResourceMetadata != nil {
		in, out := &in.ACKResourceMetadata, &out.ACKResourceMetadata
		*out = new(corev1alpha1.ResourceMetadata)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]*corev1alpha1.Condition, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(corev1alpha1.Condition)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.InferenceProfileID != nil {
		in, out := &in.InferenceProfileID, &out.InferenceProfileID
		*out = new(string)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InferenceProfileStatus.
func (in *InferenceProfileStatus) DeepCopy() *InferenceProfileStatus {
	if in == nil {
		return nil
	}
	out := new(InferenceProfileStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InferenceProfileSummary) DeepCopyInto(out *InferenceProfileSummary) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.InferenceProfileARN != nil {
		in, out := &in.InferenceProfileARN, &out.InferenceProfileARN
		*out = new(string)
		**out = **in
	}
	if in.InferenceProfileID != nil {
		in, out := &in.InferenceProfileID, &out.InferenceProfileID
		*out = new(string)
		**out = **in
	}
	if in.InferenceProfileName != nil {
		in, out := &in.InferenceProfileName, &out.InferenceProfileName
		*out = new(string)
		**out = **in
	}
	if in.Models != nil {
		in, out := &in.Models, &out.Models
		*out = make([]*InferenceProfileModel, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(InferenceProfileModel)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InferenceProfileSummary.
func (in *InferenceProfileSummary) DeepCopy() *InferenceProfileSummary {
	if in == nil {
		return nil
	}
	out := new(InferenceProfileSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MarketplaceModelEndpoint) DeepCopyInto(out *MarketplaceModelEndpoint) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MarketplaceModelEndpoint.
func (in *MarketplaceModelEndpoint) DeepCopy() *MarketplaceModelEndpoint {
	if in == nil {
		return nil
	}
	out := new(MarketplaceModelEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MarketplaceModelEndpointSummary) DeepCopyInto(out *MarketplaceModelEndpointSummary) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MarketplaceModelEndpointSummary.
func (in *MarketplaceModelEndpointSummary) DeepCopy() *MarketplaceModelEndpointSummary {
	if in == nil {
		return nil
	}
	out := new(MarketplaceModelEndpointSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelCopyJobSummary) DeepCopyInto(out *ModelCopyJobSummary) {
	*out = *in
	if in.CreationTime != nil {
		in, out := &in.CreationTime, &out.CreationTime
		*out = (*in).DeepCopy()
	}
	if in.TargetModelTags != nil {
		in, out := &in.TargetModelTags, &out.TargetModelTags
		*out = make([]*Tag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Tag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelCopyJobSummary.
func (in *ModelCopyJobSummary) DeepCopy() *ModelCopyJobSummary {
	if in == nil {
		return nil
	}
	out := new(ModelCopyJobSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelCustomizationJobSummary) DeepCopyInto(out *ModelCustomizationJobSummary) {
	*out = *in
	if in.CreationTime != nil {
		in, out := &in.CreationTime, &out.CreationTime
		*out = (*in).DeepCopy()
	}
	if in.EndTime != nil {
		in, out := &in.EndTime, &out.EndTime
		*out = (*in).DeepCopy()
	}
	if in.LastModifiedTime != nil {
		in, out := &in.LastModifiedTime, &out.LastModifiedTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelCustomizationJobSummary.
func (in *ModelCustomizationJobSummary) DeepCopy() *ModelCustomizationJobSummary {
	if in == nil {
		return nil
	}
	out := new(ModelCustomizationJobSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelImportJobSummary) DeepCopyInto(out *ModelImportJobSummary) {
	*out = *in
	if in.CreationTime != nil {
		in, out := &in.CreationTime, &out.CreationTime
		*out = (*in).DeepCopy()
	}
	if in.EndTime != nil {
		in, out := &in.EndTime, &out.EndTime
		*out = (*in).DeepCopy()
	}
	if in.LastModifiedTime != nil {
		in, out := &in.LastModifiedTime, &out.LastModifiedTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelImportJobSummary.
func (in *ModelImportJobSummary) DeepCopy() *ModelImportJobSummary {
	if in == nil {
		return nil
	}
	out := new(ModelImportJobSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelInvocationJobSummary) DeepCopyInto(out *ModelInvocationJobSummary) {
	*out = *in
	if in.EndTime != nil {
		in, out := &in.EndTime, &out.EndTime
		*out = (*in).DeepCopy()
	}
	if in.JobExpirationTime != nil {
		in, out := &in.JobExpirationTime, &out.JobExpirationTime
		*out = (*in).DeepCopy()
	}
	if in.LastModifiedTime != nil {
		in, out := &in.LastModifiedTime, &out.LastModifiedTime
		*out = (*in).DeepCopy()
	}
	if in.SubmitTime != nil {
		in, out := &in.SubmitTime, &out.SubmitTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelInvocationJobSummary.
func (in *ModelInvocationJobSummary) DeepCopy() *ModelInvocationJobSummary {
	if in == nil {
		return nil
	}
	out := new(ModelInvocationJobSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PromptRouterSummary) DeepCopyInto(out *PromptRouterSummary) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PromptRouterSummary.
func (in *PromptRouterSummary) DeepCopy() *PromptRouterSummary {
	if in == nil {
		return nil
	}
	out := new(PromptRouterSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProvisionedModelSummary) DeepCopyInto(out *ProvisionedModelSummary) {
	*out = *in
	if in.CommitmentExpirationTime != nil {
		in, out := &in.CommitmentExpirationTime, &out.CommitmentExpirationTime
		*out = (*in).DeepCopy()
	}
	if in.CreationTime != nil {
		in, out := &in.CreationTime, &out.CreationTime
		*out = (*in).DeepCopy()
	}
	if in.FoundationModelARN != nil {
		in, out := &in.FoundationModelARN, &out.FoundationModelARN
		*out = new(string)
		**out = **in
	}
	if in.LastModifiedTime != nil {
		in, out := &in.LastModifiedTime, &out.LastModifiedTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProvisionedModelSummary.
func (in *ProvisionedModelSummary) DeepCopy() *ProvisionedModelSummary {
	if in == nil {
		return nil
	}
	out := new(ProvisionedModelSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Tag) DeepCopyInto(out *Tag) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Tag.
func (in *Tag) DeepCopy() *Tag {
	if in == nil {
		return nil
	}
	out := new(Tag)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrainingDetails) DeepCopyInto(out *TrainingDetails) {
	*out = *in
	if in.CreationTime != nil {
		in, out := &in.CreationTime, &out.CreationTime
		*out = (*in).DeepCopy()
	}
	if in.LastModifiedTime != nil {
		in, out := &in.LastModifiedTime, &out.LastModifiedTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrainingDetails.
func (in *TrainingDetails) DeepCopy() *TrainingDetails {
	if in == nil {
		return nil
	}
	out := new(TrainingDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValidationDetails) DeepCopyInto(out *ValidationDetails) {
	*out = *in
	if in.CreationTime != nil {
		in, out := &in.CreationTime, &out.CreationTime
		*out = (*in).DeepCopy()
	}
	if in.LastModifiedTime != nil {
		in, out := &in.LastModifiedTime, &out.LastModifiedTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValidationDetails.
func (in *ValidationDetails) DeepCopy() *ValidationDetails {
	if in == nil {
		return nil
	}
	out := new(ValidationDetails)
	in.DeepCopyInto(out)
	return out
}
